/**
 匹配帖子记录表
 */
CREATE TABLE match_post(
  id  BIGINT   AUTO_INCREMENT COMMENT 'id',
  title VARCHAR(128) NOT NULL COMMENT '帖子标题',
  uri VARCHAR(128) NOT NULL COMMENT '路径',
  content VARCHAR(10240) NOT NULL COMMENT '匹配的内容',
  keyword VARCHAR(32) NOT NULL COMMENT '匹配的关键词',
  create_time  TIMESTAMP     DEFAULT CURRENT_TIMESTAMP
  COMMENT '创建时间',
  update_time  TIMESTAMP     DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
  COMMENT '修改时间',
  PRIMARY KEY (id),
  INDEX (keyword)
) AUTO_INCREMENT = 1000, COMMENT = '匹配帖子记录表';